name: simple-posts-app

volumes:
  db-data:
    name: "PostingDatabase"

services:
# Web Application
  posting-frontend:
    build: ./PostingWebpage
    container_name: posting_frontend
    restart: "no"
    ports:
      - "8080:8080"
    links:
      - posting-backend
    environment:
      docker: "true"
  
  # API
  posting-backend:
    build: ./PostingAPI
    container_name: posting_backend
    restart: "no"
    ports:
      - "81:80"
      - "433:433"
    volumes:
      - "./PostingAPI/logs:/var/www/html/PostingAPI/logs"
    environment:
      docker: "true"
  
  # PHP Database  
  posting-database:
    image: mysql:latest
    container_name: posting_database
    restart: "no"
    ports:
      - 3307:3306
    volumes:
      - "./testDatabase/schema:/docker-entrypoint-initdb.d"
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=r00T
      - MYSQL_DATABASE=postingDB
      - MYSQL_USER=username
      - MYSQL_PASSWORD=password