name: SimplePostingApp
services:
# Web Application
  simple-frontend:
    build: ./vueapp
    container_name: simple_frontend
    restart: "no"
    ports:
      - "8080:8080"
    links:
      - simple-backend
    environment:
      docker: "true"
  
  # API
  simple-backend:
    build: ./phpapi
    container_name: simple_backend
    restart: "no"
    ports:
      - "81:80"
      - "433:433"
    volumes:
      - "./phpapi/logs:/var/www/html/phpapi/logs"
    environment:
      docker: "true"
  
  # PHP Database  
  simple-database:
    image: mysql:latest
    container_name: simple_database
    restart: "no"
    ports:
      - 3307:3306
    volumes:
      - "./testDatabase/schema:/docker-entrypoint-initdb.d"
      #- ./testDatabase/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=r00T
      - MYSQL_DATABASE=databasePhp
      - MYSQL_USER=username
      - MYSQL_PASSWORD=password